// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/eventlog-server.proto

package getEventlog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CATEGORY int32

const (
	CATEGORY_TDX_EVENTLOG CATEGORY = 0
	CATEGORY_TPM_EVENTLOG CATEGORY = 1
)

var CATEGORY_name = map[int32]string{
	0: "TDX_EVENTLOG",
	1: "TPM_EVENTLOG",
}

var CATEGORY_value = map[string]int32{
	"TDX_EVENTLOG": 0,
	"TPM_EVENTLOG": 1,
}

func (x CATEGORY) String() string {
	return proto.EnumName(CATEGORY_name, int32(x))
}

func (CATEGORY) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3d123471d781508e, []int{0}
}

type LEVEL int32

const (
	LEVEL_PAAS LEVEL = 0
	LEVEL_SAAS LEVEL = 1
)

var LEVEL_name = map[int32]string{
	0: "PAAS",
	1: "SAAS",
}

var LEVEL_value = map[string]int32{
	"PAAS": 0,
	"SAAS": 1,
}

func (x LEVEL) String() string {
	return proto.EnumName(LEVEL_name, int32(x))
}

func (LEVEL) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3d123471d781508e, []int{1}
}

type GetEventlogRequest struct {
	EventlogLevel        LEVEL    `protobuf:"varint,1,opt,name=eventlog_level,json=eventlogLevel,proto3,enum=LEVEL" json:"eventlog_level,omitempty"`
	EventlogCategory     CATEGORY `protobuf:"varint,2,opt,name=eventlog_category,json=eventlogCategory,proto3,enum=CATEGORY" json:"eventlog_category,omitempty"`
	StartPosition        int32    `protobuf:"varint,3,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Nonce                int32    `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventlogRequest) Reset()         { *m = GetEventlogRequest{} }
func (m *GetEventlogRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventlogRequest) ProtoMessage()    {}
func (*GetEventlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d123471d781508e, []int{0}
}

func (m *GetEventlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventlogRequest.Unmarshal(m, b)
}
func (m *GetEventlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventlogRequest.Marshal(b, m, deterministic)
}
func (m *GetEventlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventlogRequest.Merge(m, src)
}
func (m *GetEventlogRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventlogRequest.Size(m)
}
func (m *GetEventlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventlogRequest proto.InternalMessageInfo

func (m *GetEventlogRequest) GetEventlogLevel() LEVEL {
	if m != nil {
		return m.EventlogLevel
	}
	return LEVEL_PAAS
}

func (m *GetEventlogRequest) GetEventlogCategory() CATEGORY {
	if m != nil {
		return m.EventlogCategory
	}
	return CATEGORY_TDX_EVENTLOG
}

func (m *GetEventlogRequest) GetStartPosition() int32 {
	if m != nil {
		return m.StartPosition
	}
	return 0
}

func (m *GetEventlogRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetEventlogRequest) GetNonce() int32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type GetEventlogReply struct {
	Nonce                int32    `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	EventlogDataLoc      string   `protobuf:"bytes,2,opt,name=eventlog_data_loc,json=eventlogDataLoc,proto3" json:"eventlog_data_loc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventlogReply) Reset()         { *m = GetEventlogReply{} }
func (m *GetEventlogReply) String() string { return proto.CompactTextString(m) }
func (*GetEventlogReply) ProtoMessage()    {}
func (*GetEventlogReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d123471d781508e, []int{1}
}

func (m *GetEventlogReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventlogReply.Unmarshal(m, b)
}
func (m *GetEventlogReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventlogReply.Marshal(b, m, deterministic)
}
func (m *GetEventlogReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventlogReply.Merge(m, src)
}
func (m *GetEventlogReply) XXX_Size() int {
	return xxx_messageInfo_GetEventlogReply.Size(m)
}
func (m *GetEventlogReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventlogReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventlogReply proto.InternalMessageInfo

func (m *GetEventlogReply) GetNonce() int32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *GetEventlogReply) GetEventlogDataLoc() string {
	if m != nil {
		return m.EventlogDataLoc
	}
	return ""
}

func init() {
	proto.RegisterEnum("CATEGORY", CATEGORY_name, CATEGORY_value)
	proto.RegisterEnum("LEVEL", LEVEL_name, LEVEL_value)
	proto.RegisterType((*GetEventlogRequest)(nil), "GetEventlogRequest")
	proto.RegisterType((*GetEventlogReply)(nil), "GetEventlogReply")
}

func init() { proto.RegisterFile("proto/eventlog-server.proto", fileDescriptor_3d123471d781508e) }

var fileDescriptor_3d123471d781508e = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xc1, 0x4f, 0xc2, 0x30,
	0x14, 0xc6, 0x99, 0x32, 0x02, 0x55, 0x70, 0x54, 0x0f, 0x8b, 0x5c, 0x08, 0x89, 0x09, 0x21, 0xd9,
	0x96, 0x60, 0xa2, 0x67, 0x84, 0x85, 0xcb, 0x14, 0x32, 0x16, 0xa2, 0x5e, 0x96, 0x52, 0xea, 0x6c,
	0x52, 0xda, 0xb9, 0x75, 0x4b, 0xf8, 0x27, 0xfd, 0x9b, 0xcc, 0x0a, 0x13, 0xc4, 0xdb, 0x7b, 0xbf,
	0xef, 0x5b, 0xf6, 0xbd, 0xbe, 0x07, 0x3a, 0x71, 0x22, 0xa4, 0x70, 0x48, 0x4e, 0xb8, 0x64, 0x22,
	0xb2, 0x52, 0x92, 0xe4, 0x24, 0xb1, 0x15, 0xed, 0x7d, 0x6b, 0x00, 0x4e, 0x89, 0x74, 0xf7, 0xa2,
	0x4f, 0xbe, 0x32, 0x92, 0x4a, 0x68, 0x81, 0x56, 0xe9, 0x0f, 0x19, 0xc9, 0x09, 0x33, 0xb5, 0xae,
	0xd6, 0x6f, 0x0d, 0x6b, 0xb6, 0xe7, 0x2e, 0x5d, 0xcf, 0x6f, 0x96, 0xaa, 0x57, 0x88, 0xf0, 0x01,
	0xb4, 0x7f, 0xed, 0x18, 0x49, 0x12, 0x89, 0x64, 0x6b, 0x9e, 0xa9, 0x2f, 0x1a, 0xf6, 0x78, 0x14,
	0xb8, 0xd3, 0x99, 0xff, 0xe6, 0x1b, 0xa5, 0x67, 0xbc, 0xb7, 0xc0, 0x3b, 0xd0, 0x4a, 0x25, 0x4a,
	0x64, 0x18, 0x8b, 0x94, 0x4a, 0x2a, 0xb8, 0x79, 0xde, 0xd5, 0xfa, 0xba, 0xdf, 0x54, 0x74, 0xbe,
	0x87, 0xf0, 0x06, 0xe8, 0x58, 0x64, 0x5c, 0x9a, 0x55, 0xa5, 0xee, 0x9a, 0x82, 0x72, 0xc1, 0x31,
	0x31, 0xf5, 0x1d, 0x55, 0x4d, 0x2f, 0x00, 0xc6, 0x9f, 0x79, 0x62, 0xb6, 0x3d, 0x38, 0xb5, 0x23,
	0x27, 0x1c, 0x1c, 0x85, 0x5e, 0x23, 0x89, 0x42, 0x26, 0xb0, 0x0a, 0xdd, 0xf0, 0xaf, 0x4a, 0x61,
	0x82, 0x24, 0xf2, 0x04, 0x1e, 0xd8, 0xa0, 0x5e, 0x8e, 0x01, 0x0d, 0x70, 0x19, 0x4c, 0x5e, 0x43,
	0x77, 0xe9, 0xbe, 0x04, 0xde, 0x6c, 0x6a, 0x54, 0x14, 0x99, 0x3f, 0x1f, 0x88, 0x36, 0xe8, 0x00,
	0x5d, 0x3d, 0x14, 0xac, 0x83, 0xea, 0x7c, 0x34, 0x5a, 0x18, 0x95, 0xa2, 0x5a, 0x14, 0x95, 0x36,
	0x1c, 0x83, 0x7a, 0x99, 0x0f, 0x3e, 0x82, 0x8b, 0xa3, 0xb8, 0xf0, 0xda, 0xfe, 0xbf, 0x8c, 0xdb,
	0xb6, 0x7d, 0x3a, 0x51, 0xaf, 0xf2, 0x84, 0xde, 0xc3, 0x88, 0xca, 0xcf, 0x6c, 0x65, 0x63, 0xb1,
	0x71, 0x28, 0x97, 0x84, 0x39, 0x58, 0xf0, 0x0f, 0xba, 0x26, 0x5c, 0x52, 0xc4, 0x2c, 0xcc, 0x44,
	0xb6, 0xb6, 0x38, 0x92, 0x34, 0x27, 0x56, 0x9c, 0xd0, 0x0d, 0x2d, 0xaa, 0xd4, 0x29, 0xd6, 0x4f,
	0x31, 0x39, 0xbd, 0x07, 0x67, 0x77, 0x25, 0xd1, 0xe1, 0x4f, 0xab, 0x9a, 0x42, 0xf7, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x5e, 0x05, 0xe5, 0x9b, 0x41, 0x02, 0x00, 0x00,
}
